### ISSUE TITLE
Invalid input issue with the `drizzle.config.ts` file when running the `db:push` command

### ISSUE THREAD

**Issue by steffancarrington** [Hendrixer/intermediate-nextjs#7]
Not sure if this is happening just for me, but I get the following error when attempting to connect the Turso DB when running the `npm run db:push` command.

` Invalid input  Either "turso", "libsql", "better-sqlite" are available options for "--driver"`

I updated the `drizzle.config.ts` file locally to remove `dialect: 'turso'` in favour of `driver: 'turso'` and this seems to fix the issue for me locally

**Comment by dtauer** [comment]
Thanks for the note! I've updated the course with an annotation about this
